[package]
name = "helloworld"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.0"
tokio = {version="1.37",features = ["full"]}

[target.'cfg(target_env = "musl")'.dependencies]
libc = "0.2.139"