# Etapa de compilación: Build environment
FROM rust:latest as build

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    musl-tools \
    && rm -rf /var/lib/apt/lists/*

# Crear y cambiar al directorio de trabajo
WORKDIR /usr/src/app

# Copiar el archivo Cargo.toml y Cargo.lock
COPY Cargo.toml Cargo.lock ./

# Copiar todo el código fuente
COPY src ./src

# Compilar el binario con el target MUSL
RUN rustup target add x86_64-unknown-linux-musl
RUN cargo build --release --target x86_64-unknown-linux-musl

### Etapa de producción: Runtime environment
FROM alpine:latest

# Copiar el binario compilado desde la etapa de compilación
COPY --from=build /usr/src/app/target/x86_64-unknown-linux-musl/release/helloworld /usr/local/bin/

# Ejecutar el binario al iniciar el contenedor
CMD ["helloworld"]
