# Stage 1: Build the Rust binary
FROM rust:latest AS builder

WORKDIR /app

COPY . .

# Build the binary
RUN cargo build --release
# Stage 2: Create a minimal runtime environment
FROM debian:buster-slim
WORKDIR /app
# Copy the built binary from the previous stage
COPY --from=builder /app/target/release/helloworld /app

# Expose the port your application runs on
EXPOSE 8000

# Command to run the binary
CMD ["./helloworld"]
